### PR TITLE
make years floating point to support greater granularity in dates and…

### PR DESCRIPTION
**Pull request by simbabque**
Hey Dave,

I saw this had a hacktoberfest tag. Not sure if this is what you were going for, it feels quite crude to use. Maybe some interface with DateTime (maybe as a subclass) or Time::Piece would be neat, so people can actually throw in a start and end date object of some kind.

Cheers!

### CODE REVIEW

**Review by davorg — APPROVED** [review]

**Comment by davorg** [comment]
I think this is a great start and I've merged it. But you're right that what I was really thinking of was to convert the start and end dates to DateTime objects.
So you'd need a coercion to convert years (numbers) and dates (strings) to DateTime objects. You'd also want a new method on DateTime (or, more likely a subclass) which gives numbers like the ones you have used here.

**Comment by simbabque** [comment]
> So you'd need a coercion to convert years (numbers) and dates (strings) to DateTime objects. 

What kind of strings where you thinking? Is there a smart DateTime::Format that we can use to guess the format?

> You'd also want a new method on DateTime (or, more likely a subclass) which gives numbers like the ones you have used here.

I was actually thinking of allowing DateTimes to go in, and coercing them into the floating numbers we have used now.

In any case, the part that calculates the differences would have to be changed. Right now the image kind of breaks if you for example give it `2017` and `2017.5`, because the max year will be `2017`.

**Comment by simbabque** [comment]
I just found this. Looks like it's been a while. Do you want me to finish this up? Or I could give it to a friend who's looking for something else to do maybe?

**Comment by davorg** [comment]
Wow. It has, hasn't it?!

I'd definitely like to see something along these lines, but just making the years floating point seems a bit of a bodge. I'd rather do something with DateTime (or Time::Piece) and DateTime::Duration (or Time::Seconds).

**Comment by simbabque** [comment]
@dave, is this now done? I saw you merged @tcheukueppo's branch, but not into master. Can we close my PR, I think he included my changes, or built on them.

**Comment by davorg** [comment]
Yeah. I'll close this. I want to rewrite the other PR to use Time::Piece. I'll do that in the next couple of days.

**Pull request closed without merging**
